[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "obfuscator"
languages = ["CXX"]
msvc-runtime = "static"

[options]
OBFUSCATOR_BUILD_TESTS = true

[conditions]
build-tests = "OBFUSCATOR_BUILD_TESTS"

[subdir.vendor]
[subdir.src]

# Ugly fix for Zydis collisions :/
cmake-after = """
set_target_properties(obfuscator obfuscator-lib obfuscator-tests zasm Zydis Zycore PROPERTIES VS_GLOBAL_VcpkgEnabled false)
"""
